# Write your MySQL query statement below

SELECT B.CLASS
FROM
(
SELECT A.CLASS , COUNT(A.CLASS) AS COUNTCL
FROM
(SELECT DISTINCT STUDENT, CLASS 
FROM COURSES
 ) A
GROUP BY CLASS
)B
WHERE B.COUNTCL >= 5